import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.imageUrl}
        alt="Profile image"
        className="h-16 w-16 rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emojis"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>...Loading</div>;

  if (!data) return <div>Something went wrong</div>;

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {user.isSignedIn && (
              <>
                <CreatePostWizard />
                <div className="flex justify-center">
                  <SignOutButton />
                </div>
              </>
            )}
          </div>
          <ul className="flex flex-col">
            {data.map(({ post, author }) => (
              <li key={post.id} className="border-b border-slate-400 p-8">
                {post.content}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
